// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: models.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from models.proto</summary>
public static partial class ModelsReflection {

  #region Descriptor
  /// <summary>File descriptor for models.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ModelsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cgxtb2RlbHMucHJvdG8iIwoMUHJvdG9Db250YWN0EhMKC3Byb3RvX3ByaW1l",
          "GAEgASgFIiMKClByb3RvSGVsbG8SFQoNcHJvdG9fbWVzc2FnZRgBIAEoCSJG",
          "CgpJdGVtSGVhZGVyEhAKCHByb3RvX2lkGAEgASgFEhIKCnByb3RvX3R5cGUY",
          "AiABKAUSEgoKcHJvdG9fc2l6ZRgDIAEoBSIuCgtQcm90b0hlYWRlchIfCgpw",
          "cm90b0l0ZW1zGAEgAygLMgsuSXRlbUhlYWRlciIqCgxQcm90b01hcHBpbmcS",
          "CwoDa2V5GAEgASgFEg0KBXZhbHVlGAIgASgJIi4KCVByb3RvSm9pbhIhCgpp",
          "eFRvUHJvdG9zGAEgAygLMg0uUHJvdG9NYXBwaW5nIk0KBFdhbGwSDwoHdmlz",
          "aWJsZRgBIAEoCBIZCgJwMRgCIAEoCzINLlByb3RvVmVjdG9yMhIZCgJwMhgD",
          "IAEoCzINLlByb3RvVmVjdG9yMiIkCgxQcm90b1ZlY3RvcjISCQoBeBgBIAEo",
          "AhIJCgF5GAIgASgCIn4KDEJ1aWxkTWF6ZU1zZxIRCgltYXplX25hbWUYASAB",
          "KAkSIgoLc3RhcnRfcG9pbnQYAiABKAsyDS5Qcm90b1ZlY3RvcjISIQoKZ29h",
          "bF9wb2ludBgEIAEoCzINLlByb3RvVmVjdG9yMhIUCgV3YWxscxgFIAMoCzIF",
          "LldhbGxiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoContact), global::ProtoContact.Parser, new[]{ "ProtoPrime" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoHello), global::ProtoHello.Parser, new[]{ "ProtoMessage" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ItemHeader), global::ItemHeader.Parser, new[]{ "ProtoId", "ProtoType", "ProtoSize" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoHeader), global::ProtoHeader.Parser, new[]{ "ProtoItems" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoMapping), global::ProtoMapping.Parser, new[]{ "Key", "Value" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoJoin), global::ProtoJoin.Parser, new[]{ "IxToProtos" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Wall), global::Wall.Parser, new[]{ "Visible", "P1", "P2" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoVector2), global::ProtoVector2.Parser, new[]{ "X", "Y" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::BuildMazeMsg), global::BuildMazeMsg.Parser, new[]{ "MazeName", "StartPoint", "GoalPoint", "Walls" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ProtoContact : pb::IMessage<ProtoContact> {
  private static readonly pb::MessageParser<ProtoContact> _parser = new pb::MessageParser<ProtoContact>(() => new ProtoContact());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ProtoContact> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ModelsReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoContact() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoContact(ProtoContact other) : this() {
    protoPrime_ = other.protoPrime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoContact Clone() {
    return new ProtoContact(this);
  }

  /// <summary>Field number for the "proto_prime" field.</summary>
  public const int ProtoPrimeFieldNumber = 1;
  private int protoPrime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ProtoPrime {
    get { return protoPrime_; }
    set {
      protoPrime_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ProtoContact);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ProtoContact other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ProtoPrime != other.ProtoPrime) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ProtoPrime != 0) hash ^= ProtoPrime.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ProtoPrime != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(ProtoPrime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ProtoPrime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProtoPrime);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ProtoContact other) {
    if (other == null) {
      return;
    }
    if (other.ProtoPrime != 0) {
      ProtoPrime = other.ProtoPrime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ProtoPrime = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class ProtoHello : pb::IMessage<ProtoHello> {
  private static readonly pb::MessageParser<ProtoHello> _parser = new pb::MessageParser<ProtoHello>(() => new ProtoHello());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ProtoHello> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ModelsReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoHello() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoHello(ProtoHello other) : this() {
    protoMessage_ = other.protoMessage_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoHello Clone() {
    return new ProtoHello(this);
  }

  /// <summary>Field number for the "proto_message" field.</summary>
  public const int ProtoMessageFieldNumber = 1;
  private string protoMessage_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ProtoMessage {
    get { return protoMessage_; }
    set {
      protoMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ProtoHello);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ProtoHello other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ProtoMessage != other.ProtoMessage) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ProtoMessage.Length != 0) hash ^= ProtoMessage.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ProtoMessage.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(ProtoMessage);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ProtoMessage.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ProtoMessage);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ProtoHello other) {
    if (other == null) {
      return;
    }
    if (other.ProtoMessage.Length != 0) {
      ProtoMessage = other.ProtoMessage;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          ProtoMessage = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class ItemHeader : pb::IMessage<ItemHeader> {
  private static readonly pb::MessageParser<ItemHeader> _parser = new pb::MessageParser<ItemHeader>(() => new ItemHeader());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ItemHeader> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ModelsReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ItemHeader() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ItemHeader(ItemHeader other) : this() {
    protoId_ = other.protoId_;
    protoType_ = other.protoType_;
    protoSize_ = other.protoSize_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ItemHeader Clone() {
    return new ItemHeader(this);
  }

  /// <summary>Field number for the "proto_id" field.</summary>
  public const int ProtoIdFieldNumber = 1;
  private int protoId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ProtoId {
    get { return protoId_; }
    set {
      protoId_ = value;
    }
  }

  /// <summary>Field number for the "proto_type" field.</summary>
  public const int ProtoTypeFieldNumber = 2;
  private int protoType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ProtoType {
    get { return protoType_; }
    set {
      protoType_ = value;
    }
  }

  /// <summary>Field number for the "proto_size" field.</summary>
  public const int ProtoSizeFieldNumber = 3;
  private int protoSize_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ProtoSize {
    get { return protoSize_; }
    set {
      protoSize_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ItemHeader);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ItemHeader other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ProtoId != other.ProtoId) return false;
    if (ProtoType != other.ProtoType) return false;
    if (ProtoSize != other.ProtoSize) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ProtoId != 0) hash ^= ProtoId.GetHashCode();
    if (ProtoType != 0) hash ^= ProtoType.GetHashCode();
    if (ProtoSize != 0) hash ^= ProtoSize.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ProtoId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(ProtoId);
    }
    if (ProtoType != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ProtoType);
    }
    if (ProtoSize != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(ProtoSize);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ProtoId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProtoId);
    }
    if (ProtoType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProtoType);
    }
    if (ProtoSize != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProtoSize);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ItemHeader other) {
    if (other == null) {
      return;
    }
    if (other.ProtoId != 0) {
      ProtoId = other.ProtoId;
    }
    if (other.ProtoType != 0) {
      ProtoType = other.ProtoType;
    }
    if (other.ProtoSize != 0) {
      ProtoSize = other.ProtoSize;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ProtoId = input.ReadInt32();
          break;
        }
        case 16: {
          ProtoType = input.ReadInt32();
          break;
        }
        case 24: {
          ProtoSize = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class ProtoHeader : pb::IMessage<ProtoHeader> {
  private static readonly pb::MessageParser<ProtoHeader> _parser = new pb::MessageParser<ProtoHeader>(() => new ProtoHeader());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ProtoHeader> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ModelsReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoHeader() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoHeader(ProtoHeader other) : this() {
    protoItems_ = other.protoItems_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoHeader Clone() {
    return new ProtoHeader(this);
  }

  /// <summary>Field number for the "protoItems" field.</summary>
  public const int ProtoItemsFieldNumber = 1;
  private static readonly pb::FieldCodec<global::ItemHeader> _repeated_protoItems_codec
      = pb::FieldCodec.ForMessage(10, global::ItemHeader.Parser);
  private readonly pbc::RepeatedField<global::ItemHeader> protoItems_ = new pbc::RepeatedField<global::ItemHeader>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::ItemHeader> ProtoItems {
    get { return protoItems_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ProtoHeader);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ProtoHeader other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!protoItems_.Equals(other.protoItems_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= protoItems_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    protoItems_.WriteTo(output, _repeated_protoItems_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += protoItems_.CalculateSize(_repeated_protoItems_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ProtoHeader other) {
    if (other == null) {
      return;
    }
    protoItems_.Add(other.protoItems_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          protoItems_.AddEntriesFrom(input, _repeated_protoItems_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class ProtoMapping : pb::IMessage<ProtoMapping> {
  private static readonly pb::MessageParser<ProtoMapping> _parser = new pb::MessageParser<ProtoMapping>(() => new ProtoMapping());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ProtoMapping> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ModelsReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoMapping() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoMapping(ProtoMapping other) : this() {
    key_ = other.key_;
    value_ = other.value_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoMapping Clone() {
    return new ProtoMapping(this);
  }

  /// <summary>Field number for the "key" field.</summary>
  public const int KeyFieldNumber = 1;
  private int key_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Key {
    get { return key_; }
    set {
      key_ = value;
    }
  }

  /// <summary>Field number for the "value" field.</summary>
  public const int ValueFieldNumber = 2;
  private string value_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Value {
    get { return value_; }
    set {
      value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ProtoMapping);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ProtoMapping other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Key != other.Key) return false;
    if (Value != other.Value) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Key != 0) hash ^= Key.GetHashCode();
    if (Value.Length != 0) hash ^= Value.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Key != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Key);
    }
    if (Value.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Value);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Key != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Key);
    }
    if (Value.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ProtoMapping other) {
    if (other == null) {
      return;
    }
    if (other.Key != 0) {
      Key = other.Key;
    }
    if (other.Value.Length != 0) {
      Value = other.Value;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Key = input.ReadInt32();
          break;
        }
        case 18: {
          Value = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class ProtoJoin : pb::IMessage<ProtoJoin> {
  private static readonly pb::MessageParser<ProtoJoin> _parser = new pb::MessageParser<ProtoJoin>(() => new ProtoJoin());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ProtoJoin> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ModelsReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoJoin() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoJoin(ProtoJoin other) : this() {
    ixToProtos_ = other.ixToProtos_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoJoin Clone() {
    return new ProtoJoin(this);
  }

  /// <summary>Field number for the "ixToProtos" field.</summary>
  public const int IxToProtosFieldNumber = 1;
  private static readonly pb::FieldCodec<global::ProtoMapping> _repeated_ixToProtos_codec
      = pb::FieldCodec.ForMessage(10, global::ProtoMapping.Parser);
  private readonly pbc::RepeatedField<global::ProtoMapping> ixToProtos_ = new pbc::RepeatedField<global::ProtoMapping>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::ProtoMapping> IxToProtos {
    get { return ixToProtos_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ProtoJoin);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ProtoJoin other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!ixToProtos_.Equals(other.ixToProtos_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= ixToProtos_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    ixToProtos_.WriteTo(output, _repeated_ixToProtos_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += ixToProtos_.CalculateSize(_repeated_ixToProtos_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ProtoJoin other) {
    if (other == null) {
      return;
    }
    ixToProtos_.Add(other.ixToProtos_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          ixToProtos_.AddEntriesFrom(input, _repeated_ixToProtos_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class Wall : pb::IMessage<Wall> {
  private static readonly pb::MessageParser<Wall> _parser = new pb::MessageParser<Wall>(() => new Wall());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Wall> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ModelsReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Wall() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Wall(Wall other) : this() {
    visible_ = other.visible_;
    P1 = other.p1_ != null ? other.P1.Clone() : null;
    P2 = other.p2_ != null ? other.P2.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Wall Clone() {
    return new Wall(this);
  }

  /// <summary>Field number for the "visible" field.</summary>
  public const int VisibleFieldNumber = 1;
  private bool visible_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Visible {
    get { return visible_; }
    set {
      visible_ = value;
    }
  }

  /// <summary>Field number for the "p1" field.</summary>
  public const int P1FieldNumber = 2;
  private global::ProtoVector2 p1_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ProtoVector2 P1 {
    get { return p1_; }
    set {
      p1_ = value;
    }
  }

  /// <summary>Field number for the "p2" field.</summary>
  public const int P2FieldNumber = 3;
  private global::ProtoVector2 p2_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ProtoVector2 P2 {
    get { return p2_; }
    set {
      p2_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Wall);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Wall other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Visible != other.Visible) return false;
    if (!object.Equals(P1, other.P1)) return false;
    if (!object.Equals(P2, other.P2)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Visible != false) hash ^= Visible.GetHashCode();
    if (p1_ != null) hash ^= P1.GetHashCode();
    if (p2_ != null) hash ^= P2.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Visible != false) {
      output.WriteRawTag(8);
      output.WriteBool(Visible);
    }
    if (p1_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(P1);
    }
    if (p2_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(P2);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Visible != false) {
      size += 1 + 1;
    }
    if (p1_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(P1);
    }
    if (p2_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(P2);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Wall other) {
    if (other == null) {
      return;
    }
    if (other.Visible != false) {
      Visible = other.Visible;
    }
    if (other.p1_ != null) {
      if (p1_ == null) {
        p1_ = new global::ProtoVector2();
      }
      P1.MergeFrom(other.P1);
    }
    if (other.p2_ != null) {
      if (p2_ == null) {
        p2_ = new global::ProtoVector2();
      }
      P2.MergeFrom(other.P2);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Visible = input.ReadBool();
          break;
        }
        case 18: {
          if (p1_ == null) {
            p1_ = new global::ProtoVector2();
          }
          input.ReadMessage(p1_);
          break;
        }
        case 26: {
          if (p2_ == null) {
            p2_ = new global::ProtoVector2();
          }
          input.ReadMessage(p2_);
          break;
        }
      }
    }
  }

}

public sealed partial class ProtoVector2 : pb::IMessage<ProtoVector2> {
  private static readonly pb::MessageParser<ProtoVector2> _parser = new pb::MessageParser<ProtoVector2>(() => new ProtoVector2());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ProtoVector2> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ModelsReflection.Descriptor.MessageTypes[7]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoVector2() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoVector2(ProtoVector2 other) : this() {
    x_ = other.x_;
    y_ = other.y_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoVector2 Clone() {
    return new ProtoVector2(this);
  }

  /// <summary>Field number for the "x" field.</summary>
  public const int XFieldNumber = 1;
  private float x_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float X {
    get { return x_; }
    set {
      x_ = value;
    }
  }

  /// <summary>Field number for the "y" field.</summary>
  public const int YFieldNumber = 2;
  private float y_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Y {
    get { return y_; }
    set {
      y_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ProtoVector2);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ProtoVector2 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
    if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (X != 0F) {
      output.WriteRawTag(13);
      output.WriteFloat(X);
    }
    if (Y != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(Y);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (X != 0F) {
      size += 1 + 4;
    }
    if (Y != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ProtoVector2 other) {
    if (other == null) {
      return;
    }
    if (other.X != 0F) {
      X = other.X;
    }
    if (other.Y != 0F) {
      Y = other.Y;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          X = input.ReadFloat();
          break;
        }
        case 21: {
          Y = input.ReadFloat();
          break;
        }
      }
    }
  }

}

public sealed partial class BuildMazeMsg : pb::IMessage<BuildMazeMsg> {
  private static readonly pb::MessageParser<BuildMazeMsg> _parser = new pb::MessageParser<BuildMazeMsg>(() => new BuildMazeMsg());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<BuildMazeMsg> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ModelsReflection.Descriptor.MessageTypes[8]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BuildMazeMsg() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BuildMazeMsg(BuildMazeMsg other) : this() {
    mazeName_ = other.mazeName_;
    StartPoint = other.startPoint_ != null ? other.StartPoint.Clone() : null;
    GoalPoint = other.goalPoint_ != null ? other.GoalPoint.Clone() : null;
    walls_ = other.walls_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BuildMazeMsg Clone() {
    return new BuildMazeMsg(this);
  }

  /// <summary>Field number for the "maze_name" field.</summary>
  public const int MazeNameFieldNumber = 1;
  private string mazeName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string MazeName {
    get { return mazeName_; }
    set {
      mazeName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "start_point" field.</summary>
  public const int StartPointFieldNumber = 2;
  private global::ProtoVector2 startPoint_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ProtoVector2 StartPoint {
    get { return startPoint_; }
    set {
      startPoint_ = value;
    }
  }

  /// <summary>Field number for the "goal_point" field.</summary>
  public const int GoalPointFieldNumber = 4;
  private global::ProtoVector2 goalPoint_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::ProtoVector2 GoalPoint {
    get { return goalPoint_; }
    set {
      goalPoint_ = value;
    }
  }

  /// <summary>Field number for the "walls" field.</summary>
  public const int WallsFieldNumber = 5;
  private static readonly pb::FieldCodec<global::Wall> _repeated_walls_codec
      = pb::FieldCodec.ForMessage(42, global::Wall.Parser);
  private readonly pbc::RepeatedField<global::Wall> walls_ = new pbc::RepeatedField<global::Wall>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::Wall> Walls {
    get { return walls_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as BuildMazeMsg);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(BuildMazeMsg other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (MazeName != other.MazeName) return false;
    if (!object.Equals(StartPoint, other.StartPoint)) return false;
    if (!object.Equals(GoalPoint, other.GoalPoint)) return false;
    if(!walls_.Equals(other.walls_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (MazeName.Length != 0) hash ^= MazeName.GetHashCode();
    if (startPoint_ != null) hash ^= StartPoint.GetHashCode();
    if (goalPoint_ != null) hash ^= GoalPoint.GetHashCode();
    hash ^= walls_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (MazeName.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(MazeName);
    }
    if (startPoint_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(StartPoint);
    }
    if (goalPoint_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(GoalPoint);
    }
    walls_.WriteTo(output, _repeated_walls_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (MazeName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MazeName);
    }
    if (startPoint_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartPoint);
    }
    if (goalPoint_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(GoalPoint);
    }
    size += walls_.CalculateSize(_repeated_walls_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(BuildMazeMsg other) {
    if (other == null) {
      return;
    }
    if (other.MazeName.Length != 0) {
      MazeName = other.MazeName;
    }
    if (other.startPoint_ != null) {
      if (startPoint_ == null) {
        startPoint_ = new global::ProtoVector2();
      }
      StartPoint.MergeFrom(other.StartPoint);
    }
    if (other.goalPoint_ != null) {
      if (goalPoint_ == null) {
        goalPoint_ = new global::ProtoVector2();
      }
      GoalPoint.MergeFrom(other.GoalPoint);
    }
    walls_.Add(other.walls_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          MazeName = input.ReadString();
          break;
        }
        case 18: {
          if (startPoint_ == null) {
            startPoint_ = new global::ProtoVector2();
          }
          input.ReadMessage(startPoint_);
          break;
        }
        case 34: {
          if (goalPoint_ == null) {
            goalPoint_ = new global::ProtoVector2();
          }
          input.ReadMessage(goalPoint_);
          break;
        }
        case 42: {
          walls_.AddEntriesFrom(input, _repeated_walls_codec);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
